global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'orchestrator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['orchestrator:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'faas-nodes'
    static_configs:
      - targets:
          - 'impute-missing-values:80'
          - 'stats:80'
          - 'export-csv:80'
          - 'read-csv:80'
          - 'filter-df:80'
          - 'drop-columns:80'
          - 'sort-columns:80'
          - 'calculate-trust-stats:80'
          - 'manage-outliers:80'
          - 'clustering-v2:80'
          - 'decision-tree-basic:80'
          - 'import-text-data:80'
          - 'import-online-data:80'
          - 'export-to-file:80'
          - 'neural-network:80'

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:24001']
